Include android_replacements.h in SpecialProtocol.cpp because mkdtemp() is not declared on android
Error was: "/SpecialProtocol.cpp:236:26: error: 'mkdtemp' was not declared
in this scope"